# Generated by Django 3.2.4 on 2021-08-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdeyes', '0002_imagetb_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFood',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=20, null=True)),
                ('dt', models.DateField(blank=True, null=True)),
                ('meal_type', models.IntegerField(blank=True, null=True)),
                ('food_name', models.CharField(blank=True, max_length=20, null=True)),
                ('food_kcal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
